name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true

      - name: Verify Node.js version
        run: node -v

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Run scraper
        run: npm start

      - name: Upload scraped data
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: public/data/
